# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
is_live: true
permalink: pretty
title: socket
email: info@socket.co.nz
phone: 027 771 0072
facebook: https://www.facebook.com/socketnz
facebookName: socketnz
twitter: https://www.facebook.com/socketnz
twitterHandle: socketnz
description: >
  Powerful apps for Mortgage Advisers, their clients, and assessors.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.socket.co.nz" # the base hostname & protocol for your site
company_name: riceKernel

home:
  tagline: SOCKET
  blurb: A smarter suite of tools for mortgage advisers and their clients

contact:
  title: Contact us
  blurb: Contact us using the form below, or sign-up for a free trial using the free trial link above

contactBorrowers:
  title: Find an adviser
  blurb: For a better home loan experience, submit your details and we'll arrange for one of our advisers to contact you quick smart

# Build settings
markdown: kramdown
