# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
is_live: false
permalink: pretty
title: Socket
email: socket@ricekernel.com
phone: 021 717 419
description: >
  Powerful tools for lending professionals and their clients.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://socket.co.nz" # the base hostname & protocol for your site
company_name: riceKernel

home:
  tagline: Socket
  blurb: Powerful tools for lending professionals and their clients

contact:
  title: Contact us
  blurb: Contact us using the form or directly through email

# Build settings
markdown: kramdown
